apiVersion: v1
kind: Pod
metadata:
  name: java-web-service-pod
spec:
  containers:
  - name: java-web-service-container
    image: docker.io/nagabhushanamn/java-web-service:batch8
    volumeMounts:
    - name: log-data
      mountPath: /app/log
  - name: log-reader-container
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - name: log-data
      mountPath: /var/log
  volumes:
  - name: log-data
    # emptyDir: {}  
    hostPath:
      path: /var/log
      type: DirectoryOrCreate
  