apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-rc
spec:
  replicas: 5
  selector:
    app: nginx  
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        region: chennai
        env: prod
    spec:
      containers:
      - image: nginx:1.11.7
        name: nginx-container
      - image: alpine
        name: alpine-container 
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

   