
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo

